var data = {
			  "TH": 
			  {
			    "title": "เนื้อเรื่อง",
                "CharStory":
                 "เนื้อเรื่องตัวละคร",
			    "description": 
				    "AftonและEmily หุ้นส่วนทางธุรกิจที่เปิดร้านอาหาร Fredbear’s Family Diner ซึ่งเป็นร้านอาหารเพื่อความบันเทิงสำหรับเด็กรูปแบบใหม่ ที่โดดเด่นด้วยหุ่นยนต์ร้องเพลง โครงการที่พวกเขาทุ่มเทอย่างเต็มที่นี้ทำให้เราได้รู้จักกับสองตัวละครที่เป็นสัญลักษณ์ของแฟรนไชส์ ​​ได้แก่ yellow Fredbearและyellow Bonnie the Bunnyสิ่งที่ทำให้ร้านอาหารของพวกเขาแตกต่างจากคู่แข่งคือสิ่งประดิษฐ์ปฏิวัติวงการของ Afton: “Springlock Suits” ต่างจากมาสคอตทั่วไปที่ใช้คนสวมชุดราคาถูก ชุดเหล่านี้เป็นเครื่องจักรที่ใช้งานได้สองวัตถุประสงค์ โดยใช้มือหมุนเพื่อหมุนชิ้นส่วนโครงกระดูกภายในแบบ animatronic กลับเข้าไปในผนังด้านในของชุดทำให้คนสามารถสวมเข้าไปและแสดงได้ วิสัยทัศน์ของ Afton สำหรับชุดเหล่านี้คือการทำให้ความฝันของเด็กๆ เป็นจริงและทำให้ animatronic ดูสมจริงที่สุดเท่าที่จะเป็นไปได้เหล่าชายทั้งสองจะสวมชุดมาสคอตเพื่อสร้างความบันเทิงให้กับเด็กๆ Emily จะสวมชุดมาสคอตหมีสีทองชื่อ Fredbear ซึ่งต่อมาเป็นที่รู้จักในแฟรนไชส์ว่า “Golden Freddy” ในขณะที่ Afton จะสวมชุดมาสคอตตัวที่สอง คือชุดกระต่ายสีทองซึ่งต่อมาเป็นที่รู้จักในแฟรนไชส์ว่า “Spring Bonnie” ผมคาดเดาว่าความทุ่มเทของพวกเขาต่อโครงการนี้อาจมาจากค่านิยมที่เน้นครอบครัวเป็นหลัก Afton มีลูกสามคน คือ  Elizabeth, Michael และ “Crying Child” ส่วน Emily มีลูกสาวหนึ่งคน คือ Charlotteเมื่อธุรกิจเติบโตขึ้น แอฟตันและเอมิลี่จึงขยายกิจการและเปิด Fazbear Entertainment ซึ่งเป็นเครือร้านอาหาร Freddy Fazbear's Pizza จำนวนมาสคอตก็เพิ่มขึ้นเช่นกัน และต่อมาก็มีตัวละครที่เราคุ้นเคยและชื่นชอบ ได้แก่ ฟ็อกซี่โจรสลัด ชิก้าไก่ และบอนนี่กระต่ายเวอร์ชั่นใหม่ ในช่วงเวลานี้ เอมิลี่ได้สร้างแอนิเมโทรนิกส์ใหม่ๆ เช่น ตุ๊กตาเฟรดแบร์ที่มีกล้องซ่อนอยู่ข้างใน (ของขวัญสำหรับลูกชายของเขา) และสาขา Funtime Animatronics ธุรกิจกำลังเฟื่องฟู และดูเหมือนว่าจะไม่มีอะไรผิดพลาดได้เลย... จนกระทั่ง... เหตุการณ์ The Bite of 1983",
                    "CharBonnie":
                    "Bonnie the Rabbit ดอะ แรบบิท เป็นหนึ่งในหุ่นยนต์แอนิเมโทรนิกส์ดั้งเดิมสี่ตัวของร้านพิซซ่าเฟรดดี้ ฟาซแบร์ และเป็นตัวร้ายหลักในซีรีส์เกม Five Nights at Freddy's Bonnie เป็นหุ่นยนต์กระต่ายและเป็นมือกีตาร์ในวงดนตรีของเฟรดดี้ ตั้งอยู่ทางด้านซ้ายของเวที โดยที่บริษัท Fazbear Entertainment, Inc. และสาธารณชนไม่รู้ มีการบอกเป็นนัยๆ ว่าบอนนี่ถูกวิญญาณที่ไม่สงบของ Jeremy เด็กชายที่ถูก William Afton ฆาตกรรมเข้าสิง ด้วยเหตุนี้ เขาและหุ่นยนต์ตัวอื่นๆ จึงออกตามล่าล้างแค้นฆาตกรด้วยการโจมตีผู้ใหญ่ในร้านพิซซ่าหลังเวลาทำการด้วยความโกรธแค้นอย่างบ้าคลั่ง",
                    "CharChica":
                    "Chica the Chicken หรือที่รู้จักกันในชื่อ Chica เป็นหนึ่งในหุ่นยนต์แอนิเมโทรนิกส์ดั้งเดิมสี่ตัวของร้านพิซซ่าเฟรดดี้ ฟาซแบร์ และเป็นตัวร้ายหลักในซีรีส์เกม Five Nights at Freddy's Chica เป็นหุ่นยนต์ไก่และเป็นนักร้องประสานเสียงในวงดนตรีของ Freddy's โดยประจำอยู่ที่ด้านขวาของเวที โดยที่บริษัท Fazbear Entertainment, Inc. และสาธารณชนไม่ได้เปิดเผยเรื่องนี้ ชิกาถูกสิงโดยวิญญาณที่ไม่สงบของ Susie  เด็กหญิงตัวน้อยที่ ถูกWilliam Afton ฆาตกรรม ด้วยเหตุนี้ เธอและหุ่นยนต์ตัวอื่นๆ จึงกำลังแก้แค้นฆาตกรของพวกเธอโดยการโจมตีผู้ใหญ่ในร้านพิซซ่าหลังเวลาทำการด้วยความโกรธแค้นอย่างบ้าคลั่ง",
                    "CharFreddyFazbear":
                    "Freddy Fazbear คือตัวร้ายหลักของซีรีส์เกม Five Nights at Freddy's และเป็นตัวละครหลักในบรรดาหุ่นยนต์แอนิเมโทรนิกส์ดั้งเดิมทั้งสี่ตัวของร้าน Freddy Fazbear's Pizza เฟรดดี้เป็นหุ่นยนต์หมีและเป็นจุดดึงดูดหลักของร้าน Freddy Fazbear's Pizza สาขาแรกที่เปิดในปี 1983 รวมถึงเป็นสัญลักษณ์และชื่อของบริษัทที่เป็นเจ้าของร้าน – Fazbear Entertainment เฟรดดี้รับบทเป็นนักร้องนำและนักแสดงหลักของวงดนตรี โดยยืนอยู่ตรงกลางเวที โดยที่ Fazbear Entertainment และสาธารณชนไม่รู้ เฟรดดี้ถูกวิญญาณที่ไม่สงบของ Gabrie – เด็กชายที่ถูก William Afton ฆาตกรรม – เข้าสิงอยู่ ด้วยเหตุนี้ เฟรดดี้และเพื่อนร่วมวงที่ถูกวิญญาณเข้าสิงเช่นกัน จึงกำลังแก้แค้นฆาตกรของพวกเขาโดยการโจมตีผู้ใหญ่ที่มีลักษณะคล้ายกันในร้านพิซซ่าหลังเวลาทำการด้วยความโกรธแค้น โดยไม่รู้ว่าเด็กเหล่านั้นกำลังถูก William Afton บงการอยู่ อย่างไรก็ตาม เฟรดดี้เป็นมิตรกับเด็ก ๆ อย่างเห็นได้ชัด และพยายามช่วยชีวิตตัวเองและเพื่อน ๆ รวมถึงเด็กคนอื่น ๆ ที่ตกเป็นเป้าหมายของ William Afton ด้วย",
                    "CharFoxy":
                    "Foxy the Pirate หรือที่รู้จักกันในชื่อ Foxy เป็นหนึ่งในหุ่นยนต์แอนิเมโทรนิกส์ดั้งเดิมสี่ตัวของร้าน Freddy Fazbear's Pizza และเป็นตัวร้ายหลักในซีรีส์เกม Five Nights at Freddy's ฟ็อกซี่เป็นหุ่นยนต์แอนิเมโทรนิกส์รูปสุนัขจิ้งจอกโจรสลัดที่เลิกผลิตไปแล้ว เขาอาศัยอยู่บนเวทีแยกต่างหากในร้านพิซซ่า โดยที่บริษัท Fazbear Entertainment, Inc. และสาธารณชนไม่ได้เปิดเผย Foxy ถูกสิงโดยวิญญาณที่ไม่สงบของ Fritz เด็กชายที่ถูก William Afton ฆาตกรรม ด้วยเหตุนี้ เขาและหุ่นยนต์ตัวอื่นๆ จึงกำลังแก้แค้นฆาตกรของพวกเขาโดยการโจมตีผู้ใหญ่ในร้านพิซซ่าหลังเวลาทำการด้วยความโกรธแค้นอย่างบ้าคลั่ง",
			  },
			  "ENG": 
			  {
			    "title": "Story",
                "CharStory": 
                "CharactorStory",
			    "description": 
				    "Before there were any of the beloved animatronics we know today, there were two men and their dream for creation: William Afton and Henry Emily. Afton and Emily were business partners who opened Fredbear’s Family Diner, a new brand of children’s entertainment restaurant that involved singing animatronics. This passion project for these men introduced us to the two iconic faces of the franchise: a yellow Fredbear and a yellow Bonnie the Bunny. What set their diner apart from competitors was Afton’s revolutionary invention: “Springlock Suits.” Unlike the standard mascots that had people in cheap suits, these were dual-purpose machines. By using a hand crank to wind the animatronic endoskeleton parts back into the inner wall of the suit, a human could slip inside and perform. Afton’s vision for these suits was to keep the children’s dreams alive and make the animatronics as realistic as possible. The men would don their suits to entertain the children. Emily would be in the titular golden Fredbear mascot, later known in the franchise as “Golden Freddy,” while Afton would be in the secondary mascot, a golden rabbit costume, later known in the franchise as “Spring Bonnie.” I speculate their dedication to the passion project might stem from the men’s family-oriented values. Afton had three children: Elizabeth, Michael and the “Crying Child.” Emily had one daughter: Charlotte.As their business grew, Afton and Emily expanded and opened “Fazbear Entertainment,” a chain of Freddy Fazbear’s Pizza restaurants. The number of mascots grew as well and then came the characters we know and love: Foxy the Pirate, Chica the Chicken and a fresh version of Bonnie the Rabbit. During this time, Emily created new animatronics, like a Fredbear Plush with a camera hidden inside of it (a gift for his son) and a branch of “Funtime Animatronics.” Business was booming, and it seemed as if nothing could go wrong … that was until … The Bite of ‘1983.",
                    "CharBonnie":
                    "Bonnie the Rabbit is one of the four original animatronics of Freddy Fazbear's Pizza and a major antagonist in the Five Nights at Freddy's series Bonnie is an animatronic rabbit and the guitarist in Freddy's band, positioned at the left side of the stage. Undisclosed to Fazbear Entertainment, Inc. and the public, Bonnie is heavily implied to be possessed by the restless spirit of Jeremy – a little boy murdered by William Afton. Due to this, he and the others are now seeking revenge against their killer by attacking any adults in the pizzeria after-hours in a blind rage.",
                    "CharChica":
                    "Chica the Chicken, also known as Chica, is one of the four original animatronics of Freddy Fazbear's Pizza and a major antagonist in the Five Nights at Freddy's series Chica is an animatronic chicken and the backup singer in Freddy's band, positioned at the right side of the stage. Undisclosed to Fazbear Entertainment, Inc. and the public, Chica is possessed by the restless spirit of Susie – a little girl murdered by William Afton. Due to this, she and the others are now seeking revenge against their killer by attacking any adults in the pizzeria after-hours in blind rage.",
                    "CharFreddyFazbear":
                    "Freddy Fazbear is the titular antagonist of the Five Nights at Freddy's series and the main of the four original animatronics of Freddy Fazbear's Pizza Freddy is an animatronic bear and the star attraction of the original Freddy Fazbear's Pizza opened in 1983,[4] as well as the face and namesake of the company that owns it– Fazbear Entertainment. Freddy takes the role of lead singer and overall performer of the band, standing in the center of the stage. Undisclosed to Fazbear Entertainment and the public, Freddy is heavily implied to be possessed by the restless spirit of Gabriel – a little boy murdered by William Afton. Due to this, Freddy and his likewise possessed bandmates are now seeking revenge against their common killer by attacking any similar-looking adults in the pizzeria after hours in a blind rage, not knowing that they, the children, are being manipulated by William Afton. However, Freddy is evidently friendly towards children and seeks to save his and his friends own souls as well as any other children targeted by William Afton.",
                    "CharFoxy":
                    "Foxy the Pirate, also known as Foxy, is one of the four original animatronics of Freddy Fazbear's Pizza and a major antagonist in the Five Nights at Freddy's series.Foxy is a discontinued animatronic pirate fox entertainer. He resides at his own separate stage in the pizzeria. Undisclosed to Fazbear Entertainment, Inc. and the public, Foxy is possessed by the restless spirit of Fritz – a little boy murdered by William Afton. Due to this, he and the others are now seeking revenge against their killer by attacking any adults in the pizzeria after-hours in blind rage.",
			  },
			}